/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vistas;

import DAO.ListaTareas;
import Modelos.Tarea;
import java.time.*;
import java.time.format.DateTimeFormatter;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author 
 */
public class VentanaAñadirTarea extends javax.swing.JFrame {

    private DefaultTableModel modeloTabla; // referencia al modelo de la tabla principal
    private ListaTareas listaTareas;
    private String usuario; 
    /**
     * Creates new form VentanaAñadirTarea
     */
    // constructor que recibe el modelo de la tabla principal

     public VentanaAñadirTarea(DefaultTableModel modelo, String usuario) {
        initComponents();
        this.modeloTabla = modelo;
        this.listaTareas = new ListaTareas();
        this.usuario = usuario;
    
        
        setLocationRelativeTo(null);
        setResizable(false);
        setSize(500,550);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        tituloAñadirtarea = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        lblNombre = new javax.swing.JLabel();
        lblAsignatura = new javax.swing.JLabel();
        lblFechaInicio = new javax.swing.JLabel();
        lblFechaEntrega = new javax.swing.JLabel();
        txtAsignatura = new javax.swing.JTextField();
        btnGuardar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        txtFechainicio = new com.toedter.calendar.JDateChooser();
        txtFechaentrega = new com.toedter.calendar.JDateChooser();
        txtdfondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setForeground(new java.awt.Color(204, 204, 204));
        jPanel1.setPreferredSize(new java.awt.Dimension(800, 500));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tituloAñadirtarea.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 36)); // NOI18N
        tituloAñadirtarea.setForeground(new java.awt.Color(255, 255, 255));
        tituloAñadirtarea.setText("Añadir Tarea");
        jPanel1.add(tituloAñadirtarea, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 40, 220, 30));
        jPanel1.add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 130, 240, 30));

        lblNombre.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 18)); // NOI18N
        lblNombre.setForeground(new java.awt.Color(255, 255, 255));
        lblNombre.setText("Nombre:");
        jPanel1.add(lblNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 130, -1, -1));

        lblAsignatura.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 18)); // NOI18N
        lblAsignatura.setForeground(new java.awt.Color(255, 255, 255));
        lblAsignatura.setText("Asignatura: ");
        jPanel1.add(lblAsignatura, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 180, -1, 30));

        lblFechaInicio.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 18)); // NOI18N
        lblFechaInicio.setForeground(new java.awt.Color(255, 255, 255));
        lblFechaInicio.setText("Fecha de inicio:");
        jPanel1.add(lblFechaInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 240, -1, -1));

        lblFechaEntrega.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 18)); // NOI18N
        lblFechaEntrega.setForeground(new java.awt.Color(255, 255, 255));
        lblFechaEntrega.setText("Fecha de entrega:");
        jPanel1.add(lblFechaEntrega, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 300, -1, -1));

        txtAsignatura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAsignaturaActionPerformed(evt);
            }
        });
        jPanel1.add(txtAsignatura, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 180, 230, 30));

        btnGuardar.setBackground(new java.awt.Color(100, 160, 100));
        btnGuardar.setFont(new java.awt.Font("Yu Gothic Medium", 1, 18)); // NOI18N
        btnGuardar.setForeground(new java.awt.Color(255, 255, 255));
        btnGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/aprobar.png"))); // NOI18N
        btnGuardar.setText(" Guardar");
        btnGuardar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnGuardar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnGuardar.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });
        jPanel1.add(btnGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 390, 150, 40));

        btnCancelar.setBackground(new java.awt.Color(170, 90, 90));
        btnCancelar.setFont(new java.awt.Font("Yu Gothic Medium", 1, 18)); // NOI18N
        btnCancelar.setForeground(new java.awt.Color(255, 255, 255));
        btnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/cancelar.png"))); // NOI18N
        btnCancelar.setText(" Cancelar");
        btnCancelar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnCancelar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCancelar.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnCancelar.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        jPanel1.add(btnCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 390, 150, 40));
        jPanel1.add(txtFechainicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 240, 180, 30));
        jPanel1.add(txtFechaentrega, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 300, 200, 30));

        txtdfondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/fondo 2.png"))); // NOI18N
        jPanel1.add(txtdfondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(-270, -450, 2120, 1300));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-40, 0, 690, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
// Abrimos la ventana principal
        VentanaPrincipal ventana = new VentanaPrincipal(usuario);
        ventana.setVisible(true);
        this.dispose(); // Cierra Añadir tareas
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
 try {
        String nombre = txtNombre.getText().trim();
        String asignatura = txtAsignatura.getText().trim();

        if (nombre.isEmpty() || asignatura.isEmpty()) {
            JOptionPane.showMessageDialog(this, "⚠️ Todos los campos son obligatorios.");
            return;
        }

        if (txtFechainicio.getDate() == null || txtFechaentrega.getDate() == null) {
            JOptionPane.showMessageDialog(this, "⚠️ Debes seleccionar ambas fechas.");
            return;
        }

        LocalDate fechaInicio = txtFechainicio.getDate().toInstant()
                .atZone(ZoneId.systemDefault()).toLocalDate();
        LocalDate fechaEntrega = txtFechaentrega.getDate().toInstant()
                .atZone(ZoneId.systemDefault()).toLocalDate();

        if (fechaEntrega.isBefore(fechaInicio)) {
            JOptionPane.showMessageDialog(this, "⚠️ La fecha de entrega no puede ser antes de la fecha de inicio.");
            return;
        }

        // Crear tarea
        Tarea tarea = new Tarea(nombre, asignatura, fechaInicio, fechaEntrega, usuario);

        // ✅ Insertar tarea en la lista y guardar en archivo inmediatamente
        listaTareas.insertarTarea(tarea);
        listaTareas.guardar(); // <--- esto asegura que VentanaPrincipal pueda leerla

        // Agregar inmediatamente al modelo de tabla
        modeloTabla.addRow(new Object[]{
            modeloTabla.getRowCount() + 1,
            tarea.getNombre(),
            tarea.getId(),
            tarea.getAsignatura(),
            tarea.getFechaInicio(),
            tarea.getFechaEntrega(),
            tarea.getPrioridad()
        });

        JOptionPane.showMessageDialog(this, "✅ Tarea guardada exitosamente.");
        this.dispose(); // Cierra ventana añadir tarea

    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "❌ Error al guardar tarea: " + e.getMessage());
        e.printStackTrace();
    }

        
        // TODO add your handling code here:
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void txtAsignaturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAsignaturaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAsignaturaActionPerformed
    
    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblAsignatura;
    private javax.swing.JLabel lblFechaEntrega;
    private javax.swing.JLabel lblFechaInicio;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel tituloAñadirtarea;
    private javax.swing.JTextField txtAsignatura;
    private com.toedter.calendar.JDateChooser txtFechaentrega;
    private com.toedter.calendar.JDateChooser txtFechainicio;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JLabel txtdfondo;
    // End of variables declaration//GEN-END:variables
}
