/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vistas;

import DAO.ListaTareas;
import Modelos.Tarea;
import Modelos.Usuario;
import java.util.List;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author HP
 */
public class VentanaPrincipal extends javax.swing.JFrame {
private String usuarioLogeado;

    /**
     * Creates new form VentanaPrincipal
     */
     public VentanaPrincipal(String usuario) {
        initComponents();
        this.usuarioLogeado = usuario;
        DefaultTableModel modelo = (DefaultTableModel) tblTareas.getModel();
        tblTareas.setDefaultEditor(Object.class, null); // Desactiva edición de todas las celdas de la tabla
           cargarTareasEnTabla();
    }
    
private void cargarTareasEnTabla() {
    try {
        ListaTareas listaTareas = new ListaTareas();
        listaTareas.cargar(); // Cargar tareas desde archivo .DAT

        DefaultTableModel modelo = (DefaultTableModel) tblTareas.getModel();
        modelo.setRowCount(0); // limpiar tabla

        int pos = 1;
        for (Tarea t : listaTareas.getLista()) {
            if (t.getUsuario().equals(usuarioLogeado)) { // ✅ Solo las del usuario logeado
                modelo.addRow(new Object[]{
                    pos++,
                    t.getNombre(),
                    t.getId(),
                    t.getAsignatura(),
                    t.getFechaInicio(),
                    t.getFechaEntrega(),
                    t.getPrioridad()
                });
            }
        }
    } catch (Exception e) {
        System.out.println("Error cargando tareas: " + e.getMessage());
    }
}


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblTareas = new javax.swing.JTable();
        tituloTareas = new javax.swing.JLabel();
        btnAtras = new javax.swing.JButton();
        btnActualizartarea = new javax.swing.JButton();
        btnAnadirtarea = new javax.swing.JButton();
        btnEliminartarea = new javax.swing.JButton();
        btnBuscartarea = new javax.swing.JButton();
        txtFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setPreferredSize(new java.awt.Dimension(800, 500));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jScrollPane2.setForeground(new java.awt.Color(255, 255, 255));

        tblTareas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Posicion", "Nombre", "ID", "Asignatura", "Fecha de inicio", "Fecha de entrega", "Prioridad"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tblTareas);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, 710, 220));

        tituloTareas.setBackground(new java.awt.Color(255, 255, 255));
        tituloTareas.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 36)); // NOI18N
        tituloTareas.setForeground(new java.awt.Color(255, 255, 255));
        tituloTareas.setText("TAREAS");
        jPanel1.add(tituloTareas, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 20, 130, -1));

        btnAtras.setBackground(new java.awt.Color(100, 100, 100));
        btnAtras.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N
        btnAtras.setForeground(new java.awt.Color(255, 255, 255));
        btnAtras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/regresar.png"))); // NOI18N
        btnAtras.setText("Atras");
        btnAtras.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtrasActionPerformed(evt);
            }
        });
        jPanel1.add(btnAtras, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 440, 110, 40));

        btnActualizartarea.setBackground(new java.awt.Color(100, 140, 170));
        btnActualizartarea.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N
        btnActualizartarea.setForeground(new java.awt.Color(255, 255, 255));
        btnActualizartarea.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/actualizar-tarea.png"))); // NOI18N
        btnActualizartarea.setText("Actualizar tarea");
        jPanel1.add(btnActualizartarea, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 340, -1, 40));

        btnAnadirtarea.setBackground(new java.awt.Color(100, 160, 100));
        btnAnadirtarea.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N
        btnAnadirtarea.setForeground(new java.awt.Color(255, 255, 255));
        btnAnadirtarea.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/añadir-tarea.png"))); // NOI18N
        btnAnadirtarea.setText("Añadir tarea");
        btnAnadirtarea.setCursor(new java.awt.Cursor(java.awt.Cursor.MOVE_CURSOR));
        btnAnadirtarea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAnadirtareaActionPerformed(evt);
            }
        });
        jPanel1.add(btnAnadirtarea, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 340, 160, 40));

        btnEliminartarea.setBackground(new java.awt.Color(170, 90, 90));
        btnEliminartarea.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N
        btnEliminartarea.setForeground(new java.awt.Color(255, 255, 255));
        btnEliminartarea.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/borrar-tarea.png"))); // NOI18N
        btnEliminartarea.setText("Eliminar tarea");
        btnEliminartarea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminartareaActionPerformed(evt);
            }
        });
        jPanel1.add(btnEliminartarea, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 340, 170, 40));

        btnBuscartarea.setBackground(new java.awt.Color(120, 120, 160));
        btnBuscartarea.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N
        btnBuscartarea.setForeground(new java.awt.Color(255, 255, 255));
        btnBuscartarea.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/buscar-tarea.png"))); // NOI18N
        btnBuscartarea.setText("Buscar tarea");
        jPanel1.add(btnBuscartarea, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 340, 160, 40));

        txtFondo.setBackground(new java.awt.Color(255, 255, 255));
        txtFondo.setFont(new java.awt.Font("Tahoma", 3, 48)); // NOI18N
        txtFondo.setForeground(new java.awt.Color(255, 255, 255));
        txtFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/fondo.png"))); // NOI18N
        txtFondo.setMaximumSize(new java.awt.Dimension(1200, 824));
        txtFondo.setMinimumSize(new java.awt.Dimension(1200, 824));
        jPanel1.add(txtFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -250, 890, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAnadirtareaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnadirtareaActionPerformed
DefaultTableModel modelo = (DefaultTableModel) tblTareas.getModel();
   
        // Abrimos la ventana de Añadir tareas
    VentanaAñadirTarea ventanaAñadirTarea = new VentanaAñadirTarea(modelo, usuarioLogeado);
    ventanaAñadirTarea.setVisible(true); 
    
    
    ventanaAñadirTarea.addWindowListener(new java.awt.event.WindowAdapter() {
    @Override
    public void windowClosed(java.awt.event.WindowEvent e) {
        cargarTareasEnTabla(); // 🔁 Se actualiza y se reordena automáticamente
    }
}); // TODO add your handling code here:
    }//GEN-LAST:event_btnAnadirtareaActionPerformed

    private void btnAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtrasActionPerformed
        // Abrimos la ventana de opciones
    OpcionesTareas opcionesTareas = new OpcionesTareas(usuarioLogeado);
    opcionesTareas.setVisible(true);
    this.dispose(); // Cierra la ventana principal


// TODO add your handling code here:
    }//GEN-LAST:event_btnAtrasActionPerformed

    private void btnEliminartareaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminartareaActionPerformed


        // TODO add your handling code here:
    }//GEN-LAST:event_btnEliminartareaActionPerformed

    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizartarea;
    private javax.swing.JButton btnAnadirtarea;
    private javax.swing.JButton btnAtras;
    private javax.swing.JButton btnBuscartarea;
    private javax.swing.JButton btnEliminartarea;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tblTareas;
    private javax.swing.JLabel tituloTareas;
    private javax.swing.JLabel txtFondo;
    // End of variables declaration//GEN-END:variables
}
