package Vistas;

import DAO.ListaTareas;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.DefaultTableModel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author andre
 */
public class VentanaGestionarUsuarios extends javax.swing.JFrame {
     private ListaTareas listaTareas;
     private DefaultTableModel modeloTabla;
     private VentanaPrincipal ventanaPrincipal;
     private String usuarioLogueado; 

    // ✅ Constructor principal (usa el método cargarTareasEnTabla de la VentanaPrincipal)
  public VentanaGestionarUsuarios(VentanaPrincipal ventanaPrincipal, String usuarioLogeado) {
    initComponents();
    
    
    this.ventanaPrincipal = ventanaPrincipal;
    this.usuarioLogueado = usuarioLogeado;

    setLocationRelativeTo(null);
    setResizable(false);
    tblUsuarios.setDefaultEditor(Object.class, null);

    // ✅ Usa el método ya existente en la ventana principal
    ventanaPrincipal.cargarTareasEnTabla(tblUsuarios);
    
    // 🟢 Detectar clic en una fila para llenar los campos
tblUsuarios.addMouseListener(new java.awt.event.MouseAdapter() {
    @Override
    public void mouseClicked(java.awt.event.MouseEvent evt) {
        int fila = tblUsuarios.getSelectedRow();
        if (fila != -1) {
            // Nombre
            txtNombreUsuario.setText(tblUsuarios.getValueAt(fila, 1).toString());

            // Asignatura
            txtApellido.setText(tblUsuarios.getValueAt(fila, 3).toString());

            // Fechas (convertir String a Date)
            try {
                String fechaInicioStr = tblUsuarios.getValueAt(fila, 4).toString();
                String fechaEntregaStr = tblUsuarios.getValueAt(fila, 5).toString();

                java.time.LocalDate fechaIni = java.time.LocalDate.parse(fechaInicioStr);
                java.time.LocalDate fechaEnt = java.time.LocalDate.parse(fechaEntregaStr);

                java.util.Date fechaIniDate = java.util.Date.from(fechaIni.atStartOfDay(java.time.ZoneId.systemDefault()).toInstant());
                java.util.Date fechaEntDate = java.util.Date.from(fechaEnt.atStartOfDay(java.time.ZoneId.sys

            } catch (Exception e) {
                System.out.println("Error al convertir fechas: " + e.getMessage());
            }
        }
    }
});


}




    // ✅ Constructor vacío (solo para pruebas o ejecución independiente)
    public VentanaGestionarUsuarios() {
        initComponents();
        setLocationRelativeTo(null);
        setResizable(false);
        setSize(985, 500);

        this.listaTareas = new ListaTareas();
        this.modeloTabla = (DefaultTableModel) tblUsuarios.getModel();

  
    }



    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        tblUsuarios = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        btnEliminarTarea = new javax.swing.JButton();
        btnActualizarUsuarios = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        txtNombreUsuario = new javax.swing.JTextField();
        lblApellido = new javax.swing.JLabel();
        lblNombre = new javax.swing.JLabel();
        txtApellido = new javax.swing.JTextField();
        lblNombre1 = new javax.swing.JLabel();
        txtUsuario = new javax.swing.JTextField();
        txtContraseña = new javax.swing.JTextField();
        lblContraseña = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        btnAtras = new javax.swing.JButton();
        txtAdmistracion = new javax.swing.JLabel();
        txtFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jScrollPane2.setForeground(new java.awt.Color(255, 255, 255));

        tblUsuarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Nombre", "Apellidos", "Usuario", "Contraseña"
            }
        ));
        jScrollPane2.setViewportView(tblUsuarios);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, 680, 220));

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnEliminarTarea.setBackground(new java.awt.Color(170, 90, 90));
        btnEliminarTarea.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N
        btnEliminarTarea.setForeground(new java.awt.Color(255, 255, 255));
        btnEliminarTarea.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/Eliminar Usuario.png"))); // NOI18N
        btnEliminarTarea.setText("Eliminar Usuarios");
        btnEliminarTarea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarTareaActionPerformed(evt);
            }
        });
        jPanel1.add(btnEliminarTarea, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 160, 40));

        btnActualizarUsuarios.setBackground(new java.awt.Color(100, 160, 100));
        btnActualizarUsuarios.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N
        btnActualizarUsuarios.setForeground(new java.awt.Color(255, 255, 255));
        btnActualizarUsuarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/actualizar usuario.png"))); // NOI18N
        btnActualizarUsuarios.setText("Actualizar Usuario");
        btnActualizarUsuarios.setCursor(new java.awt.Cursor(java.awt.Cursor.MOVE_CURSOR));
        btnActualizarUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarUsuariosActionPerformed(evt);
            }
        });
        jPanel1.add(btnActualizarUsuarios, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 160, 40));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 160, 180, 150));

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtNombreUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreUsuarioActionPerformed(evt);
            }
        });
        jPanel2.add(txtNombreUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 20, 170, 30));

        lblApellido.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 18)); // NOI18N
        lblApellido.setForeground(new java.awt.Color(255, 255, 255));
        lblApellido.setText("Apellido:");
        jPanel2.add(lblApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 20, -1, 30));

        lblNombre.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 18)); // NOI18N
        lblNombre.setForeground(new java.awt.Color(255, 255, 255));
        lblNombre.setText("Nombre:");
        jPanel2.add(lblNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));
        jPanel2.add(txtApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 20, 140, 30));

        lblNombre1.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 18)); // NOI18N
        lblNombre1.setForeground(new java.awt.Color(255, 255, 255));
        lblNombre1.setText("Usuario:");
        jPanel2.add(lblNombre1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, -1, -1));

        txtUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUsuarioActionPerformed(evt);
            }
        });
        jPanel2.add(txtUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 80, 170, 30));
        jPanel2.add(txtContraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 80, 180, 30));

        lblContraseña.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 18)); // NOI18N
        lblContraseña.setForeground(new java.awt.Color(255, 255, 255));
        lblContraseña.setText("Contraseña:");
        jPanel2.add(lblContraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 80, -1, 30));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 340, 690, 130));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 700, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 240, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 700, 240));

        btnAtras.setBackground(new java.awt.Color(100, 100, 100));
        btnAtras.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N
        btnAtras.setForeground(new java.awt.Color(255, 255, 255));
        btnAtras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/regresar.png"))); // NOI18N
        btnAtras.setText("Atras");
        btnAtras.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtrasActionPerformed(evt);
            }
        });
        getContentPane().add(btnAtras, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 420, 110, 40));

        txtAdmistracion.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 36)); // NOI18N
        txtAdmistracion.setForeground(new java.awt.Color(255, 255, 255));
        txtAdmistracion.setText("Admistrar Usuarios");
        getContentPane().add(txtAdmistracion, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 20, -1, -1));

        txtFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/fondo.png"))); // NOI18N
        getContentPane().add(txtFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 990, 500));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEliminarTareaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarTareaActionPerformed
                                                 
                                                
    int filaSeleccionada = tblUsuarios.getSelectedRow();

    if (filaSeleccionada == -1) {
        JOptionPane.showMessageDialog(this, "Selecciona un Usuario para eliminar.", "Advertencia", JOptionPane.WARNING_MESSAGE);
        return;
    }

    int idTarea = Integer.parseInt(tblUsuarios.getValueAt(filaSeleccionada, 2).toString());

    int confirmacion = JOptionPane.showConfirmDialog(
        this,
        "¿Deseas eliminar esta Usuario?",
        "Confirmar eliminación",
        JOptionPane.YES_NO_OPTION
    );

    if (confirmacion == JOptionPane.YES_OPTION) {
        ListaTareas listaTareas = new ListaTareas();
        boolean eliminada = listaTareas.eliminarTarea(idTarea);

        if (eliminada) {
            // ✅ Quita la fila directamente de la tabla
            DefaultTableModel modelo = (DefaultTableModel) tblUsuarios.getModel();
            modelo.removeRow(filaSeleccionada);

            JOptionPane.showMessageDialog(this, "Usuario eliminada correctamente.");

            // ❌ NO volver a llamar a ventanaPrincipal.cargarTareasEnTabla()
            // (porque eso recarga desde archivo y vuelve a mostrar la antigua)
        } else {
            JOptionPane.showMessageDialog(this, "No se encontró la Usuario para eliminar.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }



        // TODO add your handling code here:
    }//GEN-LAST:event_btnEliminarTareaActionPerformed

    private void btnActualizarUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarUsuariosActionPerformed
                                                  
    int filaSeleccionada = tblUsuarios.getSelectedRow();

    if (filaSeleccionada == -1) {
        JOptionPane.showMessageDialog(this, "Selecciona un Usuario para actualizar.", "Advertencia", JOptionPane.WARNING_MESSAGE);
        return;
    }

    try {
        int id = Integer.parseInt(tblUsuarios.getValueAt(filaSeleccionada, 2).toString());
        String nuevoNombre = txtNombreUsuario.getText().trim();
        String nuevaAsignatura = txtApellido.getText().trim();

        // Validar fechas (con JDateChooser)
        if (fechaInicio.getDate() == null || fechaEntrega.getDate() == null) {
            JOptionPane.showMessageDialog(this, "Por favor selecciona ambas fechas.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        java.util.Date fechaIniUtil = fechaInicio.getDate();
        java.util.Date fechaEntUtil = fechaEntrega.getDate();

        java.time.LocalDate fechaIni = fechaIniUtil.toInstant().atZone(java.time.ZoneId.systemDefault()).toLocalDate();
        java.time.LocalDate fechaEnt = fechaEntUtil.toInstant().atZone(java.time.ZoneId.systemDefault()).toLocalDate();

        if (fechaEnt.isBefore(fechaIni)) {
            JOptionPane.showMessageDialog(this, "La fecha de entrega no puede ser anterior a la fecha de inicio.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Cargar lista de tareas y buscar la que coincide con el ID
        ListaTareas listaTareas = new ListaTareas();
        boolean encontrada = false;

        for (Modelos.Tarea t : listaTareas.getLista()) {
            if (t.getId() == id && t.getUsuario().equals(usuarioLogueado)) {
                t.setNombre(nuevoNombre);
                t.setAsignatura(nuevaAsignatura);
                t.setFechaInicio(fechaIni);
                t.setFechaEntrega(fechaEnt);
                t.setPrioridad(t.calcularPrioridad());
                encontrada = true;
                break;
            }
        }

        if (encontrada) {
            listaTareas.guardar();
            JOptionPane.showMessageDialog(this, "✅ Tarea actualizada correctamente.");

            // Refrescar la tabla directamente desde la principal
            ventanaPrincipal.cargarTareasEnTabla(tblUsuarios);
        } else {
            JOptionPane.showMessageDialog(this, "⚠ No se encontró la tarea a actualizar.", "Error", JOptionPane.ERROR_MESSAGE);
        }

    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "❌ Error al actualizar tarea: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
    }

 
    }//GEN-LAST:event_btnActualizarUsuariosActionPerformed

    private void txtNombreUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreUsuarioActionPerformed

    private void btnAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtrasActionPerformed
    ventanaPrincipal.setVisible(true);

    // Recargar las tareas actualizadas en la tabla de la principal
    ventanaPrincipal.cargarTareasEnTabla(ventanaPrincipal.getTblTareas());

    // Cerrar la ventana actual de gestión
    this.dispose();


    }//GEN-LAST:event_btnAtrasActionPerformed

    private void txtUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUsuarioActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizarUsuarios;
    private javax.swing.JButton btnAtras;
    private javax.swing.JButton btnEliminarTarea;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblApellido;
    private javax.swing.JLabel lblContraseña;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblNombre1;
    private javax.swing.JTable tblUsuarios;
    private javax.swing.JLabel txtAdmistracion;
    private javax.swing.JTextField txtApellido;
    private javax.swing.JTextField txtContraseña;
    private javax.swing.JLabel txtFondo;
    private javax.swing.JTextField txtNombreUsuario;
    private javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables
}
