package Vistas;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author andre
 */
public class VentanaGestionarTareas extends javax.swing.JFrame {

    /**
     * Creates new form GestionarTareas
     */
    public VentanaGestionarTareas() {
        initComponents();
        
        setLocationRelativeTo(null);
        setResizable(false);
        setSize(985, 500);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        tblTareas = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        btnEliminarTarea = new javax.swing.JButton();
        btnActualizarTarea = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        tfdPosicion = new javax.swing.JTextField();
        tfdNombre = new javax.swing.JTextField();
        tdfID = new javax.swing.JTextField();
        tfdFechaInicio = new javax.swing.JTextField();
        tfdFechaEntrega = new javax.swing.JTextField();
        ComboAsignatura = new javax.swing.JComboBox<>();
        tfdPrioridad = new javax.swing.JTextField();
        lblPrioridad = new javax.swing.JLabel();
        lblID = new javax.swing.JLabel();
        lblAsignatura = new javax.swing.JLabel();
        lblPosicion = new javax.swing.JLabel();
        lblFechaInicio = new javax.swing.JLabel();
        lblFechaEntrega = new javax.swing.JLabel();
        lblNombre = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        txtAdmistracion = new javax.swing.JLabel();
        txtFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jScrollPane2.setForeground(new java.awt.Color(255, 255, 255));

        tblTareas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Posicion", "Nombre", "ID", "Asignatura", "Fecha de inicio", "Fecha de entrega", "Prioridad"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tblTareas);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, 680, 220));

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnEliminarTarea.setBackground(new java.awt.Color(170, 90, 90));
        btnEliminarTarea.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N
        btnEliminarTarea.setForeground(new java.awt.Color(255, 255, 255));
        btnEliminarTarea.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/borrar-tarea.png"))); // NOI18N
        btnEliminarTarea.setText("Eliminar Tarea");
        btnEliminarTarea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarTareaActionPerformed(evt);
            }
        });
        jPanel1.add(btnEliminarTarea, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 160, 40));

        btnActualizarTarea.setBackground(new java.awt.Color(100, 160, 100));
        btnActualizarTarea.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N
        btnActualizarTarea.setForeground(new java.awt.Color(255, 255, 255));
        btnActualizarTarea.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/actualizar-tarea.png"))); // NOI18N
        btnActualizarTarea.setText("Actualizar Tarea");
        btnActualizarTarea.setCursor(new java.awt.Cursor(java.awt.Cursor.MOVE_CURSOR));
        btnActualizarTarea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarTareaActionPerformed(evt);
            }
        });
        jPanel1.add(btnActualizarTarea, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 160, 40));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 160, 180, 150));

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tfdPosicion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfdPosicionActionPerformed(evt);
            }
        });
        jPanel2.add(tfdPosicion, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 20, 120, 30));

        tfdNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfdNombreActionPerformed(evt);
            }
        });
        jPanel2.add(tfdNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 80, 170, 30));

        tdfID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tdfIDActionPerformed(evt);
            }
        });
        jPanel2.add(tdfID, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 20, 70, 30));

        tfdFechaInicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfdFechaInicioActionPerformed(evt);
            }
        });
        jPanel2.add(tfdFechaInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 20, 140, 30));
        jPanel2.add(tfdFechaEntrega, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 80, 140, 30));

        ComboAsignatura.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel2.add(ComboAsignatura, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 80, 140, 30));
        jPanel2.add(tfdPrioridad, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 20, 130, 30));

        lblPrioridad.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 18)); // NOI18N
        lblPrioridad.setForeground(new java.awt.Color(255, 255, 255));
        lblPrioridad.setText("Prioridad:");
        jPanel2.add(lblPrioridad, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 20, -1, -1));

        lblID.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 18)); // NOI18N
        lblID.setForeground(new java.awt.Color(255, 255, 255));
        lblID.setText("ID:");
        jPanel2.add(lblID, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 20, -1, 30));

        lblAsignatura.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 18)); // NOI18N
        lblAsignatura.setForeground(new java.awt.Color(255, 255, 255));
        lblAsignatura.setText("Asignatura: ");
        jPanel2.add(lblAsignatura, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 80, -1, 30));

        lblPosicion.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 18)); // NOI18N
        lblPosicion.setForeground(new java.awt.Color(255, 255, 255));
        lblPosicion.setText("Posicion:");
        jPanel2.add(lblPosicion, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, 30));

        lblFechaInicio.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 18)); // NOI18N
        lblFechaInicio.setForeground(new java.awt.Color(255, 255, 255));
        lblFechaInicio.setText("Fecha de inicio:");
        jPanel2.add(lblFechaInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 20, -1, -1));

        lblFechaEntrega.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 18)); // NOI18N
        lblFechaEntrega.setForeground(new java.awt.Color(255, 255, 255));
        lblFechaEntrega.setText("Fecha de entrega:");
        jPanel2.add(lblFechaEntrega, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 80, -1, -1));

        lblNombre.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 18)); // NOI18N
        lblNombre.setForeground(new java.awt.Color(255, 255, 255));
        lblNombre.setText("Nombre:");
        jPanel2.add(lblNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, -1, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 340, 920, 130));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 700, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 240, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 700, 240));

        txtAdmistracion.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 36)); // NOI18N
        txtAdmistracion.setForeground(new java.awt.Color(255, 255, 255));
        txtAdmistracion.setText("Admistrar Tareas");
        getContentPane().add(txtAdmistracion, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 20, -1, -1));

        txtFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/fondo.png"))); // NOI18N
        getContentPane().add(txtFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 990, 500));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEliminarTareaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarTareaActionPerformed

        // TODO add your handling code here:
    }//GEN-LAST:event_btnEliminarTareaActionPerformed

    private void btnActualizarTareaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarTareaActionPerformed
        
        
    }//GEN-LAST:event_btnActualizarTareaActionPerformed

    private void tfdPosicionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfdPosicionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfdPosicionActionPerformed

    private void tfdFechaInicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfdFechaInicioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfdFechaInicioActionPerformed

    private void tdfIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tdfIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tdfIDActionPerformed

    private void tfdNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfdNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfdNombreActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaGestionarTareas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaGestionarTareas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaGestionarTareas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaGestionarTareas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaGestionarTareas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> ComboAsignatura;
    private javax.swing.JButton btnActualizarTarea;
    private javax.swing.JButton btnEliminarTarea;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblAsignatura;
    private javax.swing.JLabel lblFechaEntrega;
    private javax.swing.JLabel lblFechaInicio;
    private javax.swing.JLabel lblID;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblPosicion;
    private javax.swing.JLabel lblPrioridad;
    private javax.swing.JTable tblTareas;
    private javax.swing.JTextField tdfID;
    private javax.swing.JTextField tfdFechaEntrega;
    private javax.swing.JTextField tfdFechaInicio;
    private javax.swing.JTextField tfdNombre;
    private javax.swing.JTextField tfdPosicion;
    private javax.swing.JTextField tfdPrioridad;
    private javax.swing.JLabel txtAdmistracion;
    private javax.swing.JLabel txtFondo;
    // End of variables declaration//GEN-END:variables
}
